---
title: "Chapter6"
author: "BB"
date: "7 december 2018"
output: html_document
---


```{r}
# set working directory
setwd("C:/Users/Bram/Desktop/Open data science course/GitHub/IODS-project/data")

#read the long forms of the datasets created in data wrangling
PBRSL <- read.table(file = "BPRSL.txt", header = TRUE, sep = " ", dec = ".")
RATSL <- read.table(file = "RATSL.txt", header = TRUE, sep = " ", dec = ".")

RATS$ID <- factor(RATS$ID)
RATS$Group <- factor(RATS$Group)

#Access the package ggplot2
library(ggplot2)
library(tidyr)
library(dplyr)

# Draw the plot
RATS$Group <- factor(RATS$Group)
str(RATS$Group)
ggplot(RATSL, aes(x = Time, y = Weight, group = ID)) +
  geom_line() + facet_grid(. ~ Group, labeller = labeller(.rows = label_both, .cols = label_value)) + scale_x_continuous(name = "Time (days)", breaks = seq(0, 60, 10)) + theme(legend.position = "none") 
```




```{r}
# Standardize the weight variable
RATSL <- RATSL %>%
  group_by(Time) %>%
  mutate(stdWeight = (Weight - mean(Weight))/sd(Weight) ) %>%
  ungroup()

# Glimpse the data
glimpse(RATSL)

library(ggplot2)

# Plot again with the standardised rat weight
ggplot(RATSL, aes(x = Time, y = stdWeight, group = ID)) +
  geom_line() + facet_grid(. ~ Group, labeller = labeller(.rows = label_both, .cols = label_value)) + scale_x_continuous(name = "Time (days)", breaks = seq(0, 60, 10)) + theme(legend.position = "none") + scale_y_continuous(name = "standardized_weight")



# Number of weeks, baseline (week 0) included
n <- RATSL$Time %>% unique() %>% length()

# Summary data with mean and standard error of bprs by treatment and week 
RATSS <- RATSL %>%
  group_by(ID, Time) %>%
  summarise( mean = mean(Weight), se = sd(Weight)/sqrt(n) ) %>%
  ungroup()

glimpse(RATSS)


# Plot the mean profiles
ggplot(RATSS, aes(x = Time, y = mean, group = ID)) +
  geom_line() +
  scale_linetype_manual(values = c(1,2)) +
  geom_point(size=3) +
  scale_shape_manual(values = c(1,2)) +
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se, linetype="1"), width=0.3) +
  theme(legend.position = c(0.8,0.8)) +
  scale_y_continuous(name = "mean(Weight) +/- se(Weight)")

# Create a summary data by treatment and subject with mean as the summary variable (ignoring baseline week 0).
RATSLS <- RATSL %>%
  filter(Time > 0) %>%
  group_by(ID, Time) %>%
  summarise(mean=mean(Weight)) %>%
  ungroup()

# Glimpse the data
glimpse(RATSLS)


# Draw a boxplot of the mean versus treatment
ggplot(RATSLS, aes(x = ID, y = mean)) +
  geom_boxplot() +
  stat_summary(fun.y = "mean", geom = "point", shape=23, size=5, fill = "white") +
  scale_y_continuous(name = "mean Weight over time")

# Perform a two-sample t-test
t.test(mean ~ Time = 1,2), data = RATSLS)

# Add the baseline from the original data as a new variable to the summary data
RATSLS2 <- RATSLS %>%
  mutate(baseline = RATS$Time0)

# Fit the linear model with the mean as the response 
fit <- lm(mean ~ baseline + treatment, data = BPRSL8S2)

# Compute the analysis of variance table for the fitted model with anova()
anova(fit)


```




```{r}
# set working directory
setwd("C:/Users/Bram/Desktop/Open data science course/GitHub/IODS-project/data")

#read the long forms of the datasets created in data wrangling
PBRSL <- read.table(file = "BPRSL.txt", header = TRUE, sep = " ", dec = ".")

library(tidyr)
library(dplyr)

#plot BPRSL
ggplot(BPRSL, aes(x = week, y = bprs, linetype = subject)) +
  geom_line() +
  scale_linetype_manual(values = rep(1:10, times=4)) +
  facet_grid(. ~ treatment, labeller = label_both) +
  theme(legend.position = "none") + 
  scale_y_continuous(limits = c(min(BPRSL$bprs), max(BPRSL$bprs)))

# access library lme4
library(lme4)

# Create a random intercept model
BPRSL_ref <- lmer(bprs ~ treatment + week + (1 | subject), data = BPRSL, REML = FALSE)

# Print the summary of the model: When discarding the impact of the intercept, there's no significant effect of treatment or the week number on the bprs score.
summary(BPRSL_ref)

# create a random intercept and random slope model: When discarding the influence of the intercept and slope? 
BPRSL_ref1 <- lmer(bprs ~ treatment + week +  (treatment | subject), data = BPRSL, REML = FALSE)

# print a summary of the model: Every week the bpsr value goes down 2.27 on average. Week and treatment are not correlated
summary(BPRSL_ref1)

# perform an ANOVA test on the two models: the BPRSL_ref1 model differs significantly from the BPRSL_ref model
anova(BPRSL_ref1, BPRSL_ref)

# create a random intercept and random slope model with the interaction
BPRSL_ref2 <- lmer(bprs ~ treatment + week +  (treatment | subject) + treatment * week, data = BPRSL, REML = FALSE)

# print a summary of the model
summary(BPRSL_ref2)

# perform an ANOVA test on the two models: the ref2 model differs significantly from the ref1 model, but differences are minor when comparing to the ref and ref1 model differences.
anova(BPRSL_ref2, BPRSL_ref1)

# draw the plot of BPRSL with the observed Weight values. I need to fix the discrete and continuous issues. See if these are convertible orcheck if different graphs are possible.
ggplot(BPRSL, aes(x = week, y = treatment, group = subject)) +
  geom_line(aes(linetype = subject)) +
  scale_x_discrete(name = "Time (weeks)", breaks = seq(0, 60, 20)) +
  scale_y_discrete(name = "treatment group") +
  theme(legend.position = "top")

# Create a vector of the fitted values
Fitted <- fitted(BPRSL_ref2)

# Create a new column fitted to RATSL
BPRSL <- mutate(BPRSL, Fitted)

# draw the plot of RATSL with the Fitted values of weight
ggplot(BPRSL, aes(x = week, y = Fitted, group = subject)) +
  geom_line(aes(linetype = subject)) +
  scale_x_continuous(name = "Time (days)", breaks = seq(0, 60, 20)) +
  scale_y_continuous(name = "Fitted weight (grams)") +
  theme(legend.position = "top")

```

